default: &default
  adapter: mysql2
  timeout: 5000
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: c2s_ruby_test_development
  username: root
  password: "root"

test:
  <<: *default
  database: c2s_ruby_test_test
  username: root
  password: "root"
